include src/trunk/boot/trldr/entry/Makefile
include src/trunk/boot/trldr/startup/Makefile
include src/trunk/boot/trldr/mb2/Makefile
include src/trunk/boot/trldr/mem/Makefile
include src/trunk/boot/trldr/safety/Makefile